parameters:
#    fortune_api.example.class: JFortunato\FortuneApiBundle\Example

services:
#    fortune_api.example:
#        class: %fortune_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
